#!/home/boyuanli/tools/anaconda2/envs/python35/bin/python
# -*- coding: utf-8 -*-
import re
import sys
import sys
sys.path.append("/home/boyuanli/bashscript/bin/header")
from header_cli import cli

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())

